import type { Metadata } from "next";
import { Inter } from "next/font/google";

import "./globals.css";
import { DrawerNavbar } from "./drawer-navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Challenge | NeuralSentry",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DrawerNavbar>{children}</DrawerNavbar>
      </body>
    </html>
  );
}
