version: "3.0"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: neuralsentry-backend
    restart: unless-stopped
    # networks:
    #   - neuralsentry-net
    ports:
      - "5000:5000"
    environment:
      - DB_URL=${DB_URL}
      - PORT=5000

  # app:
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   container_name: neuralsentry-frontend
  #   restart: unless-stopped
  #   networks:
  #     - neuralsentry-net
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   environment:
  #     - NEXT_PUBLIC_API_URL=http://backend:5000/api

networks:
  neuralsentry-net:
